version: '2'
services:
  db:
    container_name: spring-boot-state-machine
    image: postgres:latest
    volumes:
      - stm_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=stm
      - POSTGRES_USER=stm
      - POSTGRES_DB=stm
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  stm_db: {}